/**
 * Seed script for Lemonize local development.
 *
 * It:
 *   1. Packs the fixture package(s) into deterministic tarballs.
 *   2. Computes sha512 (SRI) + sha256 integrity and sizes.
 *   3. Emits `seed.sql` (demo user, package, several versions, latest+beta tags,
 *      sample downloads and an audit entry).
 *   4. Writes the tarballs to `infrastructure/migrations/artifacts/` and prints
 *      the exact wrangler commands to apply the SQL and upload the artifacts
 *      to R2 so downloads work end-to-end.
 *
 * Run: `pnpm seed`
 */
import { create } from 'tar';
import { createHash, randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
// IMPORTANT: seed output lives OUTSIDE migrations_dir so wrangler never treats
// it as a migration.
const SEED_DIR = join(__dirname, '..', 'seed');
const ARTIFACTS = join(SEED_DIR, 'artifacts');
mkdirSync(ARTIFACTS, { recursive: true });
mkdirSync(SEED_DIR, { recursive: true });

function ulid(): string {
  return randomBytes(16).toString('hex');
}
const now = () => new Date().toISOString();

async function packFixture(dir: string, files: string[]): Promise<Uint8Array> {
  const chunks: Buffer[] = [];
  const stream = create({ cwd: dir, gzip: { level: 9 }, portable: true, prefix: 'package' }, files);
  await new Promise<void>((resolve, reject) => {
    stream.on('data', (c: Buffer) => chunks.push(c));
    stream.on('end', () => resolve());
    stream.on('error', reject);
  });
  return new Uint8Array(Buffer.concat(chunks));
}

function integrity(buf: Uint8Array) {
  const sri = 'sha512-' + createHash('sha512').update(buf).digest('base64');
  const shasum = createHash('sha256').update(buf).digest('hex');
  return { sri, shasum, size: buf.byteLength };
}

const sql: string[] = ['-- Generated by seed.ts. Safe to re-run after wiping the DB.', 'PRAGMA foreign_keys=OFF;'];
const esc = (s: string | null) => (s === null ? 'NULL' : `'${s.replace(/'/g, "''")}'`);

async function main() {
  const userId = ulid();
  const username = 'deepan';
  sql.push(
    `INSERT INTO users (id, username, email, created_at) VALUES (${esc(userId)}, ${esc(username)}, ${esc('deepan@example.com')}, ${esc(now())});`,
  );

  const pkgId = ulid();
  const pkgName = '@demo/utils';
  const normalized = '@demo/utils';
  const readme = readFileSync(join(ROOT, 'fixtures', 'demo-package', 'README.md'), 'utf8');
  sql.push(
    `INSERT INTO packages (id,name,normalized_name,scope,owner_user_id,organization_id,description,readme,visibility,latest_version,created_at,updated_at,deleted_at) VALUES (${esc(pkgId)}, ${esc(pkgName)}, ${esc(normalized)}, ${esc('demo')}, ${esc(userId)}, NULL, ${esc('A tiny demo utility package for Lemonize.')}, ${esc(readme)}, 'public', ${esc('1.1.0')}, ${esc(now())}, ${esc(now())}, NULL);`,
    `INSERT INTO package_maintainers (id,package_id,user_id,role,created_at) VALUES (${esc(ulid())}, ${esc(pkgId)}, ${esc(userId)}, 'owner', ${esc(now())});`,
  );

  const fixtureDir = join(ROOT, 'fixtures', 'demo-package');
  const files = ['package.json', 'dist', 'bin', 'README.md'];
  const versions = ['1.0.0', '1.1.0', '2.0.0-beta.1'];
  const manifestBase = JSON.parse(readFileSync(join(fixtureDir, 'package.json'), 'utf8'));

  for (const version of versions) {
    const manifest = { ...manifestBase, version };
    // Write a temp package.json with the right version so the tarball matches.
    writeFileSync(join(fixtureDir, 'package.json'), JSON.stringify(manifest, null, 2) + '\n');
    const buf = await packFixture(fixtureDir, files);
    const { sri, shasum, size } = integrity(buf);
    const key = `packages/@demo/utils/${version}/package.tgz`;
    const outFile = join(ARTIFACTS, `demo-utils-${version}.tgz`);
    writeFileSync(outFile, buf);

    sql.push(
      `INSERT INTO package_versions (id,package_id,version,tarball_key,integrity,shasum,unpacked_size,tarball_size,file_count,manifest_json,module_type,node_engine,bin_json,published_by,published_at,deprecated_message,yanked_at) VALUES (${esc(ulid())}, ${esc(pkgId)}, ${esc(version)}, ${esc(key)}, ${esc(sri)}, ${esc(shasum)}, ${size}, ${size}, 4, ${esc(JSON.stringify(manifest))}, 'module', '>=20', ${esc(JSON.stringify(manifest.bin))}, ${esc(userId)}, ${esc(now())}, NULL, NULL);`,
    );
  }
  // Restore fixture package.json to 1.0.0
  writeFileSync(join(fixtureDir, 'package.json'), JSON.stringify({ ...manifestBase, version: '1.0.0' }, null, 2) + '\n');

  sql.push(
    `INSERT INTO dist_tags (id,package_id,tag,version,updated_at) VALUES (${esc(ulid())}, ${esc(pkgId)}, 'latest', '1.1.0', ${esc(now())});`,
    `INSERT INTO dist_tags (id,package_id,tag,version,updated_at) VALUES (${esc(ulid())}, ${esc(pkgId)}, 'beta', '2.0.0-beta.1', ${esc(now())});`,
    `INSERT INTO downloads_daily (package_id,version,day,count) VALUES (${esc(pkgId)}, '1.1.0', ${esc(now().slice(0, 10))}, 42);`,
    `INSERT INTO downloads_daily (package_id,version,day,count) VALUES (${esc(pkgId)}, '1.0.0', ${esc(now().slice(0, 10))}, 17);`,
    `INSERT INTO publish_audit_log (id,user_id,package_id,action,detail,created_at) VALUES (${esc(ulid())}, ${esc(userId)}, ${esc(pkgId)}, 'version.publish', '@demo/utils@1.1.0', ${esc(now())});`,
  );
  sql.push('PRAGMA foreign_keys=ON;');

  const sqlPath = join(SEED_DIR, 'seed.sql');
  writeFileSync(sqlPath, sql.join('\n') + '\n');

  console.log('✔ Wrote seed.sql and artifacts.');
  console.log('\nApply the seed data locally:');
  console.log('  wrangler d1 execute lemonize_db --local --file infrastructure/seed/seed.sql');
  console.log('\nUpload the demo artifacts to R2 so downloads work:');
  for (const version of versions) {
    console.log(
      `  wrangler r2 object put lemonize-artifacts/packages/@demo/utils/${version}/package.tgz --file infrastructure/seed/artifacts/demo-utils-${version}.tgz --local`,
    );
  }
  console.log(`\nDemo API token (local only): ${rawToken}`);
}

void main();
